name: rune-vikestad

services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgresql-data:
    external: false

networks:
  default:
    driver: bridge
    external: false
