name: keycloak

services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
    external: false
