services:
  kafka:
    container_name: kafka
    hostname: kafka
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "9092:9092"
    volumes:
      # Contains custom configurations
      - kafka-data:/var/lib/kafka/data

      # Contains metadata for Kafka brokers running in KRaft mode
      - kafka-meta:/var/lib/kafka/meta
      
      # Contains default configuration
      - kafka-default-config:/opt/kafka/config
      
      # Contains custom configuration
      - kafka-shared-config:/mnt/shared/config

      # Contains operational and diagnostic logs for troubleshooting and 
      # monitoring
      - kafka-log:/var/log/kafka
      
      # Contains SSL/TLS certificates for enabling secure communication 
      # between Kafka brokers and clients
      - kafka-certs:/etc/kafka/certs      
      
      # Contains sensitive information such as passwords, API keys, or 
      # encryption keys for securing Kafka configurations and operations
      - kafka-secrets:/etc/kafka/secrets
    networks:
      - default

volumes:
  kafka-data:
    external: false
  kafka-meta:
    external: false
  kafka-config:
    external: false
  kafka-log:
    external: false
  kafka-certs:
    external: false

networks:
  default:
    driver: bridge
    external: false
