name: rune-vikestad

services:
  redis:
    container_name: redis
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - default

volumes:
  redis-data:
    external: false

networks:
  default:
    driver: bridge
    external: false
